const BUCKET_TYPES = {
  GET_BUCKETS_ERROR: "GET_BUCKETS_ERROR",
  GET_BUCKETS_STARTED: "GET_BUCKETS_STARTED",
  GET_BUCKETS_SUCCESS: "GET_BUCKETS_SUCCESS",
  CREATE_BUCKET_ERROR: "CREATE_BUCKET_ERROR",
  CREATE_BUCKET_STARTED: "CREATE_BUCKET_STARTED",
  CREATE_BUCKET_SUCCESS: "CREATE_BUCKET_SUCCESS",
  ADD_TO_BUCKET_ERROR: "ADD_TO_BUCKET_ERROR",
  ADD_TO_BUCKET_STARTED: "ADD_TO_BUCKET_STARTED",
  ADD_TO_BUCKET_SUCCESS: "ADD_TO_BUCKET_SUCCESS",
};

export default BUCKET_TYPES;
