const PROFILE_TYPES = {
  GET_COLLECTION_ERROR: "GET_COLLECTION_ERROR",
  GET_COLLECTION_STARTED: "GET_COLLECTION_STARTED",
  GET_COLLECTION_SUCCESS: "GET_COLLECTION_SUCCESS",
  INSERT_COLLECTION_ERROR: "INSERT_COLLECTION_ERROR",
  INSERT_COLLECTION_STARTED: "INSERT_COLLECTION_STARTED",
  INSERT_COLLECTION_SUCCESS: "INSERT_COLLECTION_SUCCESS",
};

export default PROFILE_TYPES;
