export const LANDING_PAGE = "/";
export const LOGIN_PAGE = "/signin";
export const HOME = "/home";
export const ABOUT = "/about";
export const SKETCH_TO_RENDER = "/sketch-to-render";
export const EXPLORE = "/explore";
export const GENERATE = "/generate";
export const PROFILE = "/profile";
export const DYNAMIC_PROFILE = "/user/:uuid";
export const EDITOR = "/editor"; //later this can be /profile:uuid/editor
export const ADD_BUCKET = "/add-bucket";
export const BUCKET = "/bucket/:bucket_id";
export const ADMIN = "/admin";
