export const LANDING_PAGE = "/";
export const HOME = "/home";
export const SKETCH_TO_RENDER = "/sketch-to-render";
export const EXPLORE = "/explore";
export const GENERATE = "/generate";
export const PROFILE = "/profile";
export const EDITOR = "/editor"; //later this can be /profile:uuid/editor
export const ADD_BUCKET = "/add-bucket";
export const BUCKET = "/bucket";
