const BUCKET_TYPES = {
  GET_NOTIFICATIONS_ERROR: "GET_NOTIFICATIONS_ERROR",
  GET_NOTIFICATIONS_SUCCESS: "GET_NOTIFICATIONS_SUCCESS",
  GET_NOTIFICATIONS_STARTED: "GET_NOTIFICATIONS_STARTED",
  SET_NOTIFICATION_STARTED: "SET_NOTIFICATION_STARTED",
  SET_NOTIFICATION_SUCCESS: "SET_NOTIFICATION_SUCCESS",
  SET_NOTIFICATION_ERROR: "SET_NOTIFICATION_ERROR",
  DELETE_NOTIFICATION_STARTED: "DELETE_NOTIFICATION_STARTED",
  DELETE_NOTIFICATION_SUCCESS: "DELETE_NOTIFICATION_SUCCESS",
  DELETE_NOTIFICATION_ERROR: "DELETE_NOTIFICATION_ERROR",
};

export default BUCKET_TYPES;
