const PROFILE_TYPES = {
  GET_GENERATED_IMAGES_ERROR: "GET_GENERATED_IMAGES_ERROR",
  GET_GENERATED_IMAGES_STARTED: "GET_GENERATED_IMAGES_STARTED",
  GET_GENERATED_IMAGES_SUCCESS: "GET_GENERATED_IMAGES_SUCCESS",
};

export default PROFILE_TYPES;
