// const PROFILE_TYPES = {
//   GET_PROFILE_ERROR: "GET_PROFILE_ERROR",
//   GET_PROFILE_STARTED: "GET_PROFILE_STARTED",
//   GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
//   UPDATE_PROFILE_ERROR: "UPDATE_PROFILE_ERROR",
//   UPDATE_PROFILE_STARTED: "UPDATE_PROFILE_STARTED",
//   UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
// };

// export default PROFILE_TYPES;
