const PROFILE_TYPES = {
  GET_PROFILE_ERROR: "GET_PROFILE_ERROR",
  GET_PROFILE_STARTED: "GET_PROFILE_STARTED",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  UPDATE_PROFILE_ERROR: "UPDATE_PROFILE_ERROR",
  UPDATE_PROFILE_STARTED: "UPDATE_PROFILE_STARTED",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  CREATE_PROFILE_ERROR: "CREATE_PROFILE_ERROR",
  CREATE_PROFILE_STARTED: "CREATE_PROFILE_STARTED",
  CREATE_PROFILE_SUCCESS: "CREATE_PROFILE_SUCCESS",
  GET_COLLECTION_ERROR: "GET_COLLECTION_ERROR",
  GET_COLLECTION_STARTED: "GET_COLLECTION_STARTED",
  GET_COLLECTION_SUCCESS: "GET_COLLECTION_SUCCESS",
};

export default PROFILE_TYPES;
