const EXPLORE_TYPES = {
  GET_EXPLORE_FEED_ERROR: "GET_EXPLORE_FEED_ERROR",
  GET_EXPLORE_FEED_STARTED: "GET_EXPLORE_FEED_STARTED",
  GET_EXPLORE_FEED_SUCCESS: "GET_EXPLORE_FEED_SUCCESS",
};

export default EXPLORE_TYPES;
