const INVITES_TYPES = {
  GET_INVITES_ERROR: "GET_INVITES_ERROR",
  GET_INVITES_STARTED: "GET_INVITES_STARTED",
  GET_INVITES_SUCCESS: "GET_INVITES_SUCCESS",
  INSERT_INVITES_ERROR: "INSERT_INVITES_ERROR",
  INSERT_INVITES_STARTED: "INSERT_INVITES_STARTED",
  INSERT_INVITES_SUCCESS: "INSERT_INVITES_SUCCESS",
  REDEEM_INVITES_IMAGE_ERROR: "REDEEM_INVITES_IMAGE_ERROR",
  REDEEM_INVITES_IMAGE_STARTED: "REDEEM_INVITES_IMAGE_STARTED",
  REDEEM_INVITES_IMAGE_SUCCESS: "REDEEM_INVITES_IMAGE_SUCCESS",
};

export default INVITES_TYPES;
