const PROFILE_TYPES = {
  GET_COLLECTION_ERROR: "GET_COLLECTION_ERROR",
  GET_COLLECTION_STARTED: "GET_COLLECTION_STARTED",
  GET_COLLECTION_SUCCESS: "GET_COLLECTION_SUCCESS",
  INSERT_COLLECTION_ERROR: "INSERT_COLLECTION_ERROR",
  INSERT_COLLECTION_STARTED: "INSERT_COLLECTION_STARTED",
  INSERT_COLLECTION_SUCCESS: "INSERT_COLLECTION_SUCCESS",
  DELETE_COLLECTION_IMAGE_ERROR: "DELETE_COLLECTION_IMAGE_ERROR",
  DELETE_COLLECTION_IMAGE_STARTED: "DELETE_COLLECTION_IMAGE_STARTED",
  DELETE_COLLECTION_IMAGE_SUCCESS: "DELETE_COLLECTION_IMAGE_SUCCESS",
};

export default PROFILE_TYPES;
